# Copyright 2024 The Sigstore Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run unit tests
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
      - '*.md'

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  model-signing-unit-tests:
    name: Signing with Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up Hatch
      uses: pypa/hatch@a3c83ab3d481fbc2dc91dd0088628817488dd1d5
    - name: Run unit tests (with coverage report at the end)
      run:  |
        hatch test -c -py ${{ matrix.python-version }} > cov.txt
        echo "VERSION=${{ matrix.python-version }} " >> $GITHUB_ENV
        echo "OS=${{ matrix.os }} " >> $GITHUB_ENV

    - name: Set environment variables
      id: env_vars
      run: |
        echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        echo "COMMIT_SHA=${{ github.sha}}" >> $GITHUB_ENV

    - name: Extract Data
      run: |
        awk '/Name/{flag=1; next} /TOTAL/{flag=0; next} flag && !/^[-]+$/' cov.txt | while read -r line; do
            # Extract file name and missing ranges
            file_name=$(echo "$line" | awk '{print $1}')
            missing_ranges=$(echo "$line" | awk '{for (i=5; i<=NF; i++) printf $i " "; print ""}')
            # Split the missing ranges by spaces (not commas as ranges are space-separated)
            IFS=' ' read -r -a ranges <<< "$missing_ranges"
            for range in "${ranges[@]}"; do
                # Process each range
                # Trim any leading or trailing whitespace
                range=$(echo "$range" | xargs)
                echo "$file_name $range" >> data.txt
            done
        done

        awk '/TOTAL/ {print $2; print $3; print $4}' cov.txt > total_cov.txt
        cat total_cov.txt


    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Specify the Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install the 'requests' library
    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/workflows/scripts/pr-coverage-comment.py total_cov.txt